// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServisBinjaket.Infrastructure.Persistence;

#nullable disable

namespace ServisBinjaket.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515155143_AddAdminAuth")]
    partial class AddAdminAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLogoutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WhatsAppPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("ALL");

                    b.Property<string>("CustomerComment")
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("ALL");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RepairRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("RepairRequestId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("ALL");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionSq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NameSq")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ShortDescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("ShortDescriptionSq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlugEn")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SlugSq")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("StockQty")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("WarrantyMonths")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SlugEn")
                        .IsUnique();

                    b.HasIndex("SlugSq")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameSq")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("SlugEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SlugSq")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("SlugEn")
                        .IsUnique();

                    b.HasIndex("SlugSq")
                        .IsUnique();

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPublished = true,
                            NameEn = "Phones",
                            NameSq = "Telefona",
                            SlugEn = "phones",
                            SlugSq = "telefona",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsPublished = true,
                            NameEn = "Laptops",
                            NameSq = "Laptopë",
                            SlugEn = "laptops",
                            SlugSq = "laptope",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsPublished = true,
                            NameEn = "Accessories",
                            NameSq = "Aksesorë",
                            SlugEn = "accessories",
                            SlugSq = "aksesore",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsPublished = true,
                            NameEn = "TV & Audio",
                            NameSq = "TV & Audio",
                            SlugEn = "tv-audio",
                            SlugSq = "tv-audio",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltEn")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AltSq")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.RepairRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerComment")
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PreferredDeliveryMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("RepairRequests");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.RepairRequestFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RepairRequestId")
                        .HasColumnType("integer");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RepairRequestId");

                    b.ToTable("RepairRequestFiles");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionSq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("NameSq")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PriceNoteEn")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PriceNoteSq")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShortDescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("ShortDescriptionSq")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SlugEn")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SlugSq")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SlugEn")
                        .IsUnique();

                    b.HasIndex("SlugSq")
                        .IsUnique();

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DescriptionEn = "Professional screen replacement service for all smartphone models.",
                            DescriptionSq = "Shërbim profesional i ndërrimit të ekranit për të gjitha modelet e smartfonëve.",
                            IsPublished = true,
                            NameEn = "Screen replacement",
                            NameSq = "Ndërrimi i ekranit",
                            PriceNoteEn = "Price depends on model",
                            PriceNoteSq = "Çmimi varet nga modeli",
                            ShortDescriptionEn = "We replace your phone screen with high quality parts.",
                            ShortDescriptionSq = "Ndërrojmë ekranin e telefonit tuaj me cilësi të lartë.",
                            SlugEn = "screen-replacement",
                            SlugSq = "nderrimi-i-ekranit"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DescriptionEn = "Our batteries are original or high quality for every model.",
                            DescriptionSq = "Bateritë tona janë origjinale ose me cilësi të lartë për çdo model.",
                            IsPublished = true,
                            NameEn = "Battery replacement",
                            NameSq = "Ndërrimi i baterisë",
                            PriceNoteEn = "Price depends on model",
                            PriceNoteSq = "Çmimi varet nga modeli",
                            ShortDescriptionEn = "We replace your old battery with a new one.",
                            ShortDescriptionSq = "Ndërrojmë baterinë e vjetër me të re.",
                            SlugEn = "battery-replacement",
                            SlugSq = "nderrimi-i-baterise"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DescriptionEn = "Professional electronic circuit repair, weak connections, damaged components.",
                            DescriptionSq = "Riparim profesional i qarkut elektronik, lidhjet e dobëta, komponentët e dëmtuar.",
                            IsPublished = true,
                            NameEn = "Soldering repair",
                            NameSq = "Riparim saldimi",
                            PriceNoteEn = "Price after diagnostics",
                            PriceNoteSq = "Çmimi pas diagnostikimit",
                            ShortDescriptionEn = "Electronic component repair with soldering.",
                            ShortDescriptionSq = "Riparim i komponentëve elektronike me saldim.",
                            SlugEn = "soldering-repair",
                            SlugSq = "riparim-saldimi"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            DescriptionEn = "Screen, keyboard, soldering, software — we fix any laptop problem.",
                            DescriptionSq = "Ekran, tastierë, saldim, softuer — riparojmë çdo problem të laptopit tuaj.",
                            IsPublished = true,
                            NameEn = "Laptop repair",
                            NameSq = "Riparim laptopi",
                            PriceNoteEn = "Price after diagnostics",
                            PriceNoteSq = "Çmimi pas diagnostikimit",
                            ShortDescriptionEn = "Full repair for laptops of any brand.",
                            ShortDescriptionSq = "Riparim i plotë i laptopëve të çdo marke.",
                            SlugEn = "laptop-repair",
                            SlugSq = "riparim-laptopi"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DescriptionEn = "We check your device and give you an accurate cost estimate before repair.",
                            DescriptionSq = "Kontrollojmë pajisjen tuaj dhe ju japim vlerësim të saktë të kostos para riparimit.",
                            IsPublished = true,
                            NameEn = "Diagnostics",
                            NameSq = "Diagnostikim",
                            PriceNoteEn = "Free",
                            PriceNoteSq = "Falas",
                            ShortDescriptionEn = "Free diagnostics of your device issue.",
                            ShortDescriptionSq = "Diagnostikim falas i problemit të pajisjes suaj.",
                            SlugEn = "diagnostics",
                            SlugSq = "diagnostikim"
                        });
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameSq")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SlugEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SlugSq")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SlugEn")
                        .IsUnique();

                    b.HasIndex("SlugSq")
                        .IsUnique();

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPublished = true,
                            NameEn = "Smartphones",
                            NameSq = "Smartphone",
                            SlugEn = "smartphones",
                            SlugSq = "smartphone",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            IsPublished = true,
                            NameEn = "Laptops",
                            NameSq = "Laptopë",
                            SlugEn = "laptops-service",
                            SlugSq = "laptope-sherbim",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            IsPublished = true,
                            NameEn = "Tablets",
                            NameSq = "Tablet",
                            SlugEn = "tablets",
                            SlugSq = "tablet",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            IsPublished = true,
                            NameEn = "Other",
                            NameSq = "Të tjera",
                            SlugEn = "other",
                            SlugSq = "te-tjera",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Order", b =>
                {
                    b.HasOne("ServisBinjaket.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ServisBinjaket.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServisBinjaket.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ServisBinjaket.Domain.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ServisBinjaket.Domain.Entities.RepairRequest", "RepairRequest")
                        .WithMany("Payments")
                        .HasForeignKey("RepairRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("RepairRequest");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Product", b =>
                {
                    b.HasOne("ServisBinjaket.Domain.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("ServisBinjaket.Domain.Entities.ProductCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("ServisBinjaket.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.RepairRequest", b =>
                {
                    b.HasOne("ServisBinjaket.Domain.Entities.Customer", "Customer")
                        .WithMany("RepairRequests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServisBinjaket.Domain.Entities.Service", "Service")
                        .WithMany("RepairRequests")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.RepairRequestFile", b =>
                {
                    b.HasOne("ServisBinjaket.Domain.Entities.RepairRequest", "RepairRequest")
                        .WithMany("Files")
                        .HasForeignKey("RepairRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepairRequest");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Service", b =>
                {
                    b.HasOne("ServisBinjaket.Domain.Entities.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("RepairRequests");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.RepairRequest", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.Service", b =>
                {
                    b.Navigation("RepairRequests");
                });

            modelBuilder.Entity("ServisBinjaket.Domain.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
